# travis-ci config file

language: java

before_install:
  - chmod +x gradlew

before_script:
 - chmod +x gradlew


jdk:
 - oraclejdk11

sudo: required

script:
 - ./gradlew clean build -i --continue


deploy:
  provider: releases
  api_key: 22df69fc7c44b8bdafa84727fbe6db2389c13c9b
  file: \build\libs\nexot-all-1.0.jar
  skip_cleanup: true
  on:
    tags: false
